Repository okex/okexchain, pull requests merged in 2020-04, with the labels that each got.

#10 replace fmt.Printf with t.Logf
  x/staking/common_test.go
  x/staking/delegator_test.go
  x/staking/validator_state_machine_test.go
  x/staking/validator_test.go
Labels: good first issue

#21 replace meaningless code comments with "// nolint" or more meaningful comments
  x/token/beginblocker.go
  x/token/beginblocker_test.go
  x/token/client/cli/query.go
  x/token/client/cli/tx.go
  x/token/client/rest/rest.go
  x/token/client/rest/rest_v2.go
  x/token/fee.go
  x/token/genesis.go
  x/token/genesis_test.go
  x/token/handler.go
  x/token/keeper.go
  x/token/keeper_test.go
  x/token/memory_cache.go
  x/token/memory_cache_test.go
  x/token/module.go
  x/token/module_basic.go
  x/token/module_test.go
  x/token/querier.go
  x/token/token_test.go
  x/token/types/keys.go
  x/token/types/msgs.go
  x/token/types/params.go
  x/token/types/token_test.go
  x/token/types/util.go
Labels: enhancement

#49 FIX: a delegator was banned from proxy regsiter with keeping binding before
  x/staking/delegator_test.go
  x/staking/handler_vote.go
  x/staking/keeper/proxy_test.go
  x/staking/types/errors.go
Labels: x/staking

#72 init the module account at the stage of initGenesis
  app/protocol/protocol_v0.go
  x/dex/genesis.go
  x/token/genesis.go
Labels: P0, bug
